services:
  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: carshop
      POSTGRES_PASSWORD: carshop_pw
      POSTGRES_DB: carshopdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U carshop -d carshopdb"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=carshopdb;Username=carshop;Password=carshop_pw
    ports:
      - "5001:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
